-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 20:00:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi_ii_iii
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `pi_ii_iii`;

CREATE SCHEMA IF NOT EXISTS `pi_ii_iii` DEFAULT CHARACTER SET utf8 ;
USE `pi_ii_iii`;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_contatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_contatos` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_contatos` (
  `idCtt` INT(11) NOT NULL AUTO_INCREMENT,
  `cttFixo` CHAR(13) NOT NULL,
  `cttCel` CHAR(13) NOT NULL,
  `cttEmail` VARCHAR(25) NOT NULL,
  `cttDtaHraCad` DATETIME NOT NULL,
  `cttUserCad` CHAR(15) NOT NULL,
  PRIMARY KEY (`idCtt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_endereco` (
  `idEnd` INT(11) NOT NULL AUTO_INCREMENT,
  `endLogradouro` VARCHAR(45) NOT NULL,
  `endNumero` INT(11) NOT NULL,
  `endBairro` VARCHAR(20) NOT NULL,
  `endCidade` VARCHAR(20) NOT NULL,
  `endCep` INT(11) NOT NULL,
  `endUF` CHAR(2) NOT NULL,
  `endComplemento` VARCHAR(45) NULL DEFAULT NULL,
  `endDtaHraCad` DATETIME NOT NULL,
  `endUserCad` CHAR(15) NOT NULL,
  PRIMARY KEY (`idEnd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`lt_ctt_end`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`lt_ctt_end` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`lt_ctt_end` (
  `idCttEnd` INT(11) NOT NULL AUTO_INCREMENT,
  `ce_fk_idCtt` INT(11) NOT NULL,
  `ce_fk_idEnd` INT(11) NOT NULL,
  PRIMARY KEY (`idCttEnd`),
  INDEX `FkIdCtt_idx` (`ce_fk_idCtt` ASC),
  INDEX `FkidEnd_idx` (`ce_fk_idEnd` ASC),
  CONSTRAINT `ceFkIdCtt`
    FOREIGN KEY (`ce_fk_idCtt`)
    REFERENCES `pi_ii_iii`.`tb_contatos` (`idCtt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ceFkidEnd`
    FOREIGN KEY (`ce_fk_idEnd`)
    REFERENCES `pi_ii_iii`.`tb_endereco` (`idEnd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_pacientes` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_pacientes` (
  `idPac` INT(11) NOT NULL AUTO_INCREMENT,
  `pacNome` VARCHAR(25) NOT NULL,
  `pacCpf` INT(11) NOT NULL,
  `pacDtaNac` DATE NOT NULL,
  `pacDtaHraCad` DATETIME NOT NULL,
  `pacUserCad` CHAR(15) NOT NULL,
  `pacLogUser` CHAR(15) NOT NULL,
  `pacLogPwd` VARCHAR(255) NOT NULL,
  `pc_fk_idCttEnd` INT(11) NOT NULL,
  PRIMARY KEY (`idPac`),
  INDEX `pcFK_idCttEnd_idx` (`pc_fk_idCttEnd` ASC),
  CONSTRAINT `pcFK_idCttEnd`
    FOREIGN KEY (`pc_fk_idCttEnd`)
    REFERENCES `pi_ii_iii`.`lt_ctt_end` (`idCttEnd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_psicologo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_psicologo` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_psicologo` (
  `idPsc` INT(11) NOT NULL AUTO_INCREMENT,
  `pscRegistro` VARCHAR(15) NOT NULL,
  `pscNome` VARCHAR(45) NOT NULL,
  `pscRegistroValidade` DATE NOT NULL,
  `pscEspecializacao` VARCHAR(45) NOT NULL,
  `pscDtaCad` DATETIME NOT NULL,
  `pscUserCad` CHAR(15) NOT NULL,
  `pscLogUser` CHAR(15) NOT NULL,
  `pscLogPwd` VARCHAR(255) NOT NULL,
  `ps_fk_IdCttEnd` INT(11) NOT NULL,
  PRIMARY KEY (`idPsc`),
  INDEX `psFK_idCttEnd_idx` (`ps_fk_IdCttEnd` ASC),
  CONSTRAINT `psFK_idCttEnd`
    FOREIGN KEY (`ps_fk_IdCttEnd`)
    REFERENCES `pi_ii_iii`.`lt_ctt_end` (`idCttEnd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_humordia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_humordia` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_humordia` (
  `idHumor` INT(11) NOT NULL AUTO_INCREMENT,
  `hmrSituacao` TINYTEXT NOT NULL,
  `hmrDescricao` TINYTEXT,
  `hmrJson` JSON,
  `hmrDtaHraCad` DATETIME NOT NULL,
  `hu_fk_idPac` INT(11) NOT NULL,
  PRIMARY KEY (`idHumor`),
  INDEX `huFK_idPac_idx` (`hu_fk_idPac` ASC),
  CONSTRAINT `huFK_idPac`
    FOREIGN KEY (`hu_fk_idPac`)
    REFERENCES `pi_ii_iii`.`tb_pacientes` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`TB_Root`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`TB_Root` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`TB_Root` (
  `idRoot` INT NOT NULL AUTO_INCREMENT,
  `rtUser` VARCHAR(15) NOT NULL,
  `rtPwd` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRoot`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`TB_Anexos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`TB_Anexos` ;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`TB_Anexos` (
  `idAnx` INT NOT NULL AUTO_INCREMENT,
  `anxDescricao` TINYTEXT NOT NULL,
  `anxFormato` ENUM('.pdf', '.png', ',jpg') NOT NULL,
  `anxCaminho` VARCHAR(255) NOT NULL,
  `anxDtaHra` DATETIME NOT NULL,
  `axfk_idPac` INT NOT NULL,
  PRIMARY KEY (`idAnx`),
  INDEX `anxFk_idPac_idx` (`axfk_idPac` ASC),
  CONSTRAINT `axFK_idPac`
    FOREIGN KEY (`axfk_idPac`)
    REFERENCES `pi_ii_iii`.`tb_pacientes` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_consultas`;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`tb_consultas` (
  `idCons` INT(11) NOT NULL AUTO_INCREMENT,
  `conDtaHraIn` DATETIME NOT NULL,
  `conDtaHraFim` DATETIME NOT NULL,
  `conResumo` TINYTEXT,
  `conFeedPscPac` TINYTEXT,
  `conFeedPacPsc` TINYTEXT,
  `conDetalhe` TEXT,
  `conDtaHraReg` DATETIME,
  `conStsLan` ENUM('0','1') DEFAULT '0',
  `conUserCad` CHAR(15) NOT NULL,
  `cs_fk_idPac` INT(11) NOT NULL,
  `cs_fk_idPsc` INT(11) NOT NULL,
  PRIMARY KEY (`idCons`),
  INDEX `csFK_idPac_idx` (`cs_fk_idPac` ASC),
  INDEX `csFK_idPsc_idx` (`cs_fk_idPsc` ASC),
  CONSTRAINT `csFK_idPac`
    FOREIGN KEY (`cs_fk_idPac`)
    REFERENCES `pi_ii_iii`.`tb_pacientes` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `csFK_idPsc`
    FOREIGN KEY (`cs_fk_idPsc`)
    REFERENCES `pi_ii_iii`.`tb_psicologo` (`idPsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pi_ii_iii`.`tb_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_ii_iii`.`tb_feedback`;

CREATE TABLE IF NOT EXISTS `pi_ii_iii`.`feedback` (
  `idCons` INT(11) NOT NULL AUTO_INCREMENT,
  `conDtaHraIn` DATETIME NOT NULL,
  `conDtaHraFim` DATETIME NOT NULL,
  `conResumo` TINYTEXT,
  `conFeedPscPac` TINYTEXT,
  `conFeedPacPsc` TINYTEXT,
  `conDetalhe` TEXT,
  `conDtaHraReg` DATETIME,
  `conStsLan` ENUM('0','1') DEFAULT '0',
  `conUserCad` CHAR(15) NOT NULL,
  `cs_fk_idPac` INT(11) NOT NULL,
  `cs_fk_idPsc` INT(11) NOT NULL,
  PRIMARY KEY (`idCons`),
  INDEX `csFK_idPac_idx` (`cs_fk_idPac` ASC),
  INDEX `csFK_idPsc_idx` (`cs_fk_idPsc` ASC),
  CONSTRAINT `csFK_idPac`
    FOREIGN KEY (`cs_fk_idPac`)
    REFERENCES `pi_ii_iii`.`tb_pacientes` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `csFK_idPsc`
    FOREIGN KEY (`cs_fk_idPsc`)
    REFERENCES `pi_ii_iii`.`tb_psicologo` (`idPsc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Insert de Usuário ROOT
-- -----------------------------------------------------
INSERT INTO `pi_ii_iii`.`TB_Root` (`idRoot`, `rtUser`, `rtPwd`) 
	VALUES ('1', 'root', '$2y$10$KG7OY300ujJox9izgzxU8ur/VnD0//ZIJPjC.zVc5ulsHIUjv4tXW');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
